### ISSUE TITLE
Clear button behaviour 

### ISSUE THREAD

**Issue by SMH110** [yaaHosein/Calculator1#1]
The clear button should clear the result div .
I added some number using the numbers buttons
![image](https://user-images.githubusercontent.com/16171515/97806874-bdf9e180-1c55-11eb-9609-5f87b0bbcfcd.png)
when I click on clear button 
this what I should see
![image](https://user-images.githubusercontent.com/16171515/97806940-ff8a8c80-1c55-11eb-9ed5-1e9756482f0d.png)

**Comment by yaaHosein** [comment]
I added some of the required codes for doing it
