### ISSUE TITLE
Improve calculating process 

### ISSUE THREAD

**Issue by SMH110** [yaaHosein/Calculator1#13]
Currently when I click on a number then an operator button (+ - * /) the number disappear immediately which looks odd and I think we should change this behaviour.

Instead of clearing the number; we should keep the number in the result div until the user enters the second number.

**Acceptance Criteria**
- user enters a number -> user sees the number in the result div
- user clicks on operator button -> user still see the first number in the result div
- user enters second number -> user sees the second number

Example:
Say I want to perform 1 + 2
I click on 1 button -> I see 1 in the result div
I click on + button -> I still see 1 in  the result div
I click on 2 button -> I see 2 in the result div 
I click on = button -> I see 3 in the result div

**Comment by yaaHosein** [comment]
it is fixed
