### ISSUE TITLE
Wrong calculation after clearing

### ISSUE THREAD

**Issue by SMH110** [yaaHosein/Calculator1#18]
I get a wrong result after performing an operation, then clearing the result and start another operation.

For example 
When I use the calculator to calculate the result of 22 + 2 then I clear to start another calculation like 2 - 1 
I get 24 

To reproduce this issue; follow the steps below:
1. click on 2 
2. click on + 
3. click on 6
4. click on = 
5. click on clear button
6. click on 2
7. click on - button

You will see 8 in the result div, But I would expect to see 2 at this point.

**Comment by yaaHosein** [comment]
why i should see 8 not 2 ?

**Comment by SMH110** [comment]
> why i should see 8 not 2 ?

I have edited the issue and change "should" to "will"

**Comment by yaaHosein** [comment]
My confusion is I am clicking on 2 and - buttons after cleaning 🧻 
So y I will see 8

**Comment by SMH110** [comment]
> My confusion is I am clicking on 2 and - buttons after cleaning 🧻
> So y I will see 8

What is confusing you now?

Currently, and because we have a bug in the clear button; when you clear then you click on operator button you will see the previous result and this is the bug.

**Comment by yaaHosein** [comment]
InshaAllah this night when I will be near the laptop 💻 I will check this bug 🐜 again 
Thanks

**Comment by SMH110** [comment]
is this bug fixed?

**Comment by yaaHosein** [comment]
yes it is

**Comment by SMH110** [comment]
Can you close this issue?

**Comment by yaaHosein** [comment]
yes i can
