### ISSUE TITLE
Divide by zero 

### ISSUE THREAD

**Issue by SMH110** [yaaHosein/Calculator1#20]
When I dived by zero; I see NaN in the result div

![image](https://user-images.githubusercontent.com/16171515/104090436-a9961e80-526e-11eb-81b1-077198bc8819.png)

to produce this bug:
1. open the calculator
2. enter a number
3. click on /
4. click on 0
5. click on =

I would expect to see 0 in the result div but I am seeing `NaN`

**Comment by yaaHosein** [comment]
you are right I had an idea about this issue

**Comment by SMH110** [comment]
Is this bug fixed?

**Comment by yaaHosein** [comment]
Yes it’s!

**Comment by SMH110** [comment]
can you close fixed/done issues?

**Comment by yaaHosein** [comment]
Yes
