### ISSUE TITLE
Wrong result after clicking the equal button

### ISSUE THREAD

**Issue by SMH110** [yaaHosein/Calculator1#24]
Open the calculator and click on:
1 
then 
+ 
then
3

then 
=

should see 3 

then click on + 
you will see  5 

I would expect t to see 3 in the result element because I didn't the second operand yet.

**Comment by yaaHosein** [comment]
I tried to see this bug in the both implementation but I did not found it 
I tried also with another operations they are working fine also

**Comment by yaaHosein** [comment]
Should I close this issue after the last pushing?!

**Comment by yaaHosein** [comment]
I have added only these code
In the line 
173:

&& this.operator !== null ;

Line 181
