### ISSUE TITLE
Show the hisotry of the calculator 

### ISSUE THREAD

**Issue by SMH110** [yaaHosein/Calculator1#27]
It will be good if we can see the performed operation in the calculator 
Something similar to this calculator app developed by Google 
![image](https://user-images.githubusercontent.com/16171515/114231687-a7795400-9972-11eb-802b-d09ed62646d4.png)

We don't want to add this feature to the current Calculator class we created in the previous PR. 
We need to create another class that inherit from Calculator class and  add the new feature to the new class

For this, you need to create another `js` file  and in the new file create a class that extends the Calcualtor class 
Please make sure to add a reference to the new js file in the index.html

**Comment by yaaHosein** [comment]
Okay 
Thanks
