### ISSUE TITLE
Add support for decimal 

### ISSUE THREAD

**Issue by SMH110** [yaaHosein/Calculator1#3]
We need to allow users entering decimal values like 1.2, 0.5 33.2 ...etc.
Users can use the period button 
![image](https://user-images.githubusercontent.com/16171515/99502929-a6b93480-2975-11eb-97eb-793437873022.png)
The period button role is to append "." to the current number displayed in the result div
If I have 1 in my result div and I click on . 
I should see 1.

**Comment by yaaHosein** [comment]
please check the comments I tried to do what you are asking
